steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lab1-434600/my-flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lab1-434600/my-flask-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'update-container', 'flask-instance', '--container-image', 'gcr.io/lab1-434600/my-flask-app', '--zone', 'us-central1-a']

images:
- 'gcr.io/lab1-434600/my-flask-app'
